name: frame_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.3.0
  tiled: 0.8.4
  flame_tiled: ^1.7.2
  flutter_riverpod: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/character/
    - assets/tiles/city.tmx
    - assets/tiles/lake.tmx
    - assets/images/tiles/未整理チップ1.png
    - assets/images/tiles/pipo-map001_at-umi.png
    - assets/images/tiles/pipo-map001.png
    - assets/tiles/未整理チップ1.tsx
    - assets/tiles/city.tsx
    - assets/tiles/pipo-map001_at-umi.tsx
    - assets/tiles/pipo-map001.tsx



